
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAppInfo() : Promise<AppInfoDto> {
    return await TAURI_INVOKE("get_app_info");
},
async getEnvironmentState() : Promise<Result<EnvironmentStateDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_environment_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 重新探测五个工具并替换环境快照。探测是同步子进程调用；`command(async)`
 * 让它在线程池执行，完成后 `AppState` 的通知回调会广播 `environment-ready`。
 */
async refreshEnvironment() : Promise<Result<EnvironmentStateDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_environment") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDashboardSummary() : Promise<Result<DashboardSummaryDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dashboard_summary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async completeOnboarding() : Promise<Result<CompleteOnboardingResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_onboarding") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSnapshots() : Promise<Result<SnapshotSummary[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_snapshots") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSnapshots(input: DeleteSnapshotsInput) : Promise<Result<DeleteSnapshotsResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_snapshots", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInterruptedRun() : Promise<Result<InterruptedRunPlan | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_interrupted_run") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewSnapshotRestore(input: SnapshotRestoreInput) : Promise<Result<RestorePreview, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_snapshot_restore", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreSnapshot(input: ApplySnapshotRestoreInput) : Promise<Result<ApplyResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_snapshot", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettingsDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAppSettings(input: UpdateAppSettingsInput) : Promise<Result<AppSettingsDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_app_settings", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProjects() : Promise<Result<ProjectDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProject(id: string) : Promise<Result<ProjectDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async registerProject(input: RegisterProjectInput) : Promise<Result<ProjectDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_project", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameProject(input: RenameProjectInput) : Promise<Result<ProjectDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_project", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rescanProject(input: VersionedProjectInput) : Promise<Result<ProjectDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rescan_project", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeProject(input: VersionedProjectInput) : Promise<Result<RemoveProjectResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_project", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProjectNativeResources(input: ProjectNativeResourceQueryInput) : Promise<Result<ProjectNativeResourceDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_project_native_resources", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewProjectNativeResourceAction(input: PreviewProjectNativeResourceActionInput) : Promise<Result<PreviewPlan, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_project_native_resource_action", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyProjectNativeResourcePreview(input: ApplyProjectNativeResourcePreviewInput) : Promise<Result<ApplyResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_project_native_resource_preview", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProviderProfiles(tool: Tool) : Promise<Result<ProviderProfileDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_provider_profiles", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createProviderProfile(input: ProviderProfileInput) : Promise<Result<ProviderProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_provider_profile", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateProviderProfile(input: UpdateProviderProfileInput) : Promise<Result<ProviderProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_provider_profile", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async copyProviderProfile(input: CopyProviderProfileInput) : Promise<Result<ProviderProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_provider_profile", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveProviderProfile(tool: Tool, input: VersionedProfileInput) : Promise<Result<ProviderProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_provider_profile", { tool, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteProviderProfile(input: VersionedProfileInput) : Promise<Result<DeleteProfileResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_provider_profile", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPromptProfiles() : Promise<Result<PromptProfileDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_prompt_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createPromptProfile(input: PromptProfileInput) : Promise<Result<PromptProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_prompt_profile", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePromptProfile(input: UpdatePromptProfileInput) : Promise<Result<PromptProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_prompt_profile", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGlobalPromptAssignment(input: SetGlobalPromptAssignmentInput) : Promise<Result<PromptProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_global_prompt_assignment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePromptProfile(input: VersionedProfileInput) : Promise<Result<DeleteProfileResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_prompt_profile", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getToolProfileStatus(tool: Tool) : Promise<Result<ToolProfileStatusDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tool_profile_status", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverProviderImport(tool: Tool) : Promise<Result<ProviderImportPreviewDto | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_provider_import", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async confirmProviderImport(input: ConfirmImportInput) : Promise<Result<ProviderProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_provider_import", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverPromptImport(tool: Tool) : Promise<Result<PromptImportPreviewDto | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_prompt_import", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async confirmPromptImport(input: ConfirmImportInput) : Promise<Result<PromptProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_prompt_import", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewProviderSync(tool: Tool) : Promise<Result<PreviewPlan, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_provider_sync", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewPromptSync(tool: Tool) : Promise<Result<PreviewPlan, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_prompt_sync", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyProfilePreview(input: ApplyProfilePreviewInput) : Promise<Result<ApplyResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_profile_preview", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 探测会同步启动一个几秒内结束的 CLI 子进程；`command(async)` 让它离开主线程。
 */
async getOfficialLoginStatus(tool: Tool) : Promise<Result<OfficialLoginStatusDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_official_login_status", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startOfficialLogin(tool: Tool) : Promise<Result<OfficialLoginStatusDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_official_login", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelOfficialLogin(tool: Tool) : Promise<Result<OfficialLoginStatusDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_official_login", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMcpServers() : Promise<Result<McpServerDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_mcp_servers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMcpServer(id: string) : Promise<Result<McpServerDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mcp_server", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createMcpServer(input: McpServerInput) : Promise<Result<McpServerDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_mcp_server", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMcpServer(input: UpdateMcpServerInput) : Promise<Result<McpServerDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_mcp_server", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMcpEnabled(input: VersionedMcpInput, enabled: boolean) : Promise<Result<McpServerDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_mcp_enabled", { input, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMcpServer(input: VersionedMcpInput) : Promise<Result<DeleteMcpResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_mcp_server", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGlobalMcpAssignment(input: SetGlobalMcpAssignmentInput) : Promise<Result<McpServerDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_global_mcp_assignment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setProjectMcpAssignment(input: SetProjectMcpAssignmentInput) : Promise<Result<McpServerDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_project_mcp_assignment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMcpProjects() : Promise<Result<McpProjectDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_mcp_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMcpProjectOptions(input: McpProjectOptionsInput) : Promise<Result<McpProjectOptionDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_mcp_project_options", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGlobalMcpTargetStatuses() : Promise<Result<McpTargetStatusDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_global_mcp_target_statuses") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewMcpSync(input: PreviewMcpSyncInput) : Promise<Result<PreviewPlan, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_mcp_sync", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyMcpPreview(input: ApplyMcpPreviewInput) : Promise<Result<ApplyResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_mcp_preview", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readoptMcpTarget(input: ReadoptMcpTargetInput) : Promise<Result<ReadoptMcpTargetResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("readopt_mcp_target", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverMcpImport(tool: Tool) : Promise<Result<McpImportPreviewDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_mcp_import", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async confirmMcpImport(input: ConfirmMcpImportInput) : Promise<Result<McpImportResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_mcp_import", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkills() : Promise<Result<SkillDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skills") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSkill(id: string) : Promise<Result<SkillDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_skill", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importSkill(input: ImportSkillInput) : Promise<Result<SkillDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_skill", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importGithubSkill(input: ImportGithubSkillInput) : Promise<Result<SkillDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_github_skill", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverSkillImport(tool: Tool) : Promise<Result<SkillImportPreviewDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_skill_import", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async confirmSkillImport(input: ConfirmSkillImportInput) : Promise<Result<SkillImportResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_skill_import", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async prepareSkillTakeover(input: PrepareSkillTakeoverInput) : Promise<Result<SkillTakeoverPreviewResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prepare_skill_takeover", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewSkillContent(id: string) : Promise<Result<SkillContentPreviewDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_skill_content", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async adoptSkillContent(input: VersionedSkillInput) : Promise<Result<SkillDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("adopt_skill_content", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSkill(input: VersionedSkillInput) : Promise<Result<DeleteSkillResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_skill", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGlobalSkillAssignment(input: SetGlobalSkillAssignmentInput) : Promise<Result<SkillDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_global_skill_assignment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setProjectSkillAssignment(input: SetProjectSkillAssignmentInput) : Promise<Result<SkillDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_project_skill_assignment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkillProjects() : Promise<Result<SkillProjectDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skill_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkillProjectOptions(input: SkillProjectOptionsInput) : Promise<Result<SkillProjectOptionDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skill_project_options", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGlobalSkillTargetStatuses() : Promise<Result<SkillTargetStatusDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_global_skill_target_statuses") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewSkillSync(input: PreviewSkillSyncInput) : Promise<Result<PreviewPlan, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_skill_sync", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applySkillPreview(input: ApplySkillPreviewInput) : Promise<Result<ApplyResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_skill_preview", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listHooks() : Promise<Result<HookDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_hooks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHook(id: string) : Promise<Result<HookDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_hook", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createHook(input: CreateHookInput) : Promise<Result<HookDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_hook", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHook(input: UpdateHookInput) : Promise<Result<HookDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_hook", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setHookEnabled(input: VersionedHookInput, enabled: boolean) : Promise<Result<HookDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_hook_enabled", { input, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHook(input: VersionedHookInput) : Promise<Result<DeleteHookResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_hook", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGlobalHookAssignment(input: SetGlobalHookAssignmentInput) : Promise<Result<HookDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_global_hook_assignment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setProjectHookAssignment(input: SetProjectHookAssignmentInput) : Promise<Result<HookDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_project_hook_assignment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listHookProjects() : Promise<Result<HookProjectDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_hook_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listHookProjectOptions(input: HookProjectOptionsInput) : Promise<Result<HookProjectOptionDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_hook_project_options", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGlobalHookTargetStatuses() : Promise<Result<HookTargetStatusDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_global_hook_target_statuses") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewHookSync(input: PreviewHookSyncInput) : Promise<Result<PreviewPlan, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_hook_sync", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyHookPreview(input: ApplyHookPreviewInput) : Promise<Result<ApplyResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_hook_preview", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readoptHookTarget(input: ReadoptHookTargetInput) : Promise<Result<ReadoptHookTargetResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("readopt_hook_target", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverHookImport(input: DiscoverHookImportInput) : Promise<Result<HookImportPreviewDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_hook_import", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async confirmHookImport(input: ConfirmHookImportInput) : Promise<Result<HookImportResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_hook_import", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAgents() : Promise<Result<AgentDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_agents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAgent(id: string) : Promise<Result<AgentDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_agent", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createAgent(input: CreateAgentInput) : Promise<Result<AgentDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_agent", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAgent(input: UpdateAgentInput) : Promise<Result<AgentDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_agent", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAgentEnabled(input: VersionedAgentInput, enabled: boolean) : Promise<Result<AgentDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_agent_enabled", { input, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAgentToolSettings(input: SetAgentToolSettingsInput) : Promise<Result<AgentDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_agent_tool_settings", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAgent(input: VersionedAgentInput) : Promise<Result<DeleteAgentResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_agent", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGlobalAgentAssignment(input: SetGlobalAgentAssignmentInput) : Promise<Result<AgentDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_global_agent_assignment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setProjectAgentAssignment(input: SetProjectAgentAssignmentInput) : Promise<Result<AgentDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_project_agent_assignment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAgentProjects() : Promise<Result<AgentProjectDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_agent_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAgentProjectOptions(input: AgentProjectOptionsInput) : Promise<Result<AgentProjectOptionDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_agent_project_options", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGlobalAgentTargetStatuses() : Promise<Result<AgentToolTargetStatusDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_global_agent_target_statuses") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewAgentSync(input: PreviewAgentSyncInput) : Promise<Result<PreviewPlan, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_agent_sync", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyAgentPreview(input: ApplyAgentPreviewInput) : Promise<Result<ApplyResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_agent_preview", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readoptAgentTarget(input: ReadoptAgentTargetInput) : Promise<Result<ReadoptAgentTargetResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("readopt_agent_target", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverAgentImport(input: DiscoverAgentImportInput) : Promise<Result<AgentImportPreviewDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_agent_import", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async confirmAgentImport(input: ConfirmAgentImportInput) : Promise<Result<AgentImportResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_agent_import", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/

export const TOOL_CAPABILITIES = [{"agentToolSettings":true,"agents":true,"hooks":true,"mcp":true,"projectAgents":true,"promptGlobal":true,"provider":true,"skills":true,"tool":"claude"},{"agentToolSettings":true,"agents":true,"hooks":true,"mcp":true,"projectAgents":true,"promptGlobal":true,"provider":true,"skills":true,"tool":"codex"},{"agentToolSettings":false,"agents":true,"hooks":true,"mcp":true,"projectAgents":true,"promptGlobal":true,"provider":false,"skills":true,"tool":"cursor"},{"agentToolSettings":false,"agents":true,"hooks":true,"mcp":true,"projectAgents":false,"promptGlobal":true,"provider":true,"skills":true,"tool":"zcode"},{"agentToolSettings":false,"agents":true,"hooks":false,"mcp":true,"projectAgents":true,"promptGlobal":true,"provider":true,"skills":true,"tool":"opencode"}] as const;
export const HOOK_EVENT_SUPPORT = [{"event":"SessionStart","tool":"claude"},{"event":"SessionEnd","tool":"claude"},{"event":"UserPromptSubmit","tool":"claude"},{"event":"PreToolUse","tool":"claude"},{"event":"PermissionRequest","tool":"claude"},{"event":"PostToolUse","tool":"claude"},{"event":"SubagentStop","tool":"claude"},{"event":"PreCompact","tool":"claude"},{"event":"Stop","tool":"claude"},{"event":"Notification","tool":"claude"},{"event":"SessionStart","tool":"codex"},{"event":"SessionEnd","tool":"codex"},{"event":"UserPromptSubmit","tool":"codex"},{"event":"PreToolUse","tool":"codex"},{"event":"PermissionRequest","tool":"codex"},{"event":"PostToolUse","tool":"codex"},{"event":"SubagentStart","tool":"codex"},{"event":"SubagentStop","tool":"codex"},{"event":"PreCompact","tool":"codex"},{"event":"PostCompact","tool":"codex"},{"event":"Stop","tool":"codex"},{"event":"SessionStart","tool":"cursor"},{"event":"SessionEnd","tool":"cursor"},{"event":"PreToolUse","tool":"cursor"},{"event":"PostToolUse","tool":"cursor"},{"event":"PostToolUseFailure","tool":"cursor"},{"event":"SubagentStart","tool":"cursor"},{"event":"SubagentStop","tool":"cursor"},{"event":"PreCompact","tool":"cursor"},{"event":"Stop","tool":"cursor"},{"event":"SessionStart","tool":"zcode"},{"event":"UserPromptSubmit","tool":"zcode"},{"event":"PreToolUse","tool":"zcode"},{"event":"PermissionRequest","tool":"zcode"},{"event":"PostToolUse","tool":"zcode"},{"event":"PostToolUseFailure","tool":"zcode"},{"event":"Stop","tool":"zcode"}] as const;

/** user-defined types **/

export type AgentDto = { id: string; name: string; description: string; prompt: string; enabled: boolean; globalAssignments: Tool[]; toolSettings: AgentToolSettingsDto; rowVersion: number }
export type AgentFileTargetStatusDto = { targetPath: string; status: SyncStatus; diagnosticCode: string | null }
export type AgentImportCandidateDto = { candidateId: string; sourcePath: string;
/**
 * 建议名称：frontmatter `name`（缺省时为文件名去扩展名）。
 */
name: string;
/**
 * 缺少必填字段时可能为空。
 */
description: string; prompt: string;
/**
 * 将被交集投影丢弃的工具特有 frontmatter / TOML 键名（知情丢弃）。
 */
droppedFields: string[];
/**
 * 将按工具白名单保留并写入覆盖层的字段名。
 */
retainedFields: string[];
/**
 * 候选确认时写入该工具覆盖层的规范化 JSON。
 */
toolSettings: JsonValue | null; importable: boolean;
/**
 * `AGENT_FRONTMATTER_INVALID` / `AGENT_REQUIRED_FIELD_MISSING` /
 * `AGENT_NAME_INVALID` / `AGENT_NAME_CONFLICT`。
 */
diagnosticCode: string | null; reason: string | null }
export type AgentImportPreviewDto = { tool: Tool; directoryPath: string; candidates: AgentImportCandidateDto[]; message: string | null }
export type AgentImportResultDto = { tool: Tool; createdCount: number }
export type AgentProjectDto = { id: string; displayName: string; rootPath: string; codexTrustStatus: TrustStatus; rowVersion: number }
export type AgentProjectOptionDto = { agentId: string; name: string; enabled: boolean; state: ManagedProjectSelectionState; selectable: boolean; rowVersion: number }
export type AgentProjectOptionsInput = { projectId: string; tool: Tool }
/**
 * Agent 的工具特有覆盖层。缺省工具或 null 表示没有覆盖。
 */
export type AgentToolSettingsDto = { claude: ClaudeAgentSettings | null; codex: CodexAgentSettings | null }
/**
 * 全局目标状态卡按工具聚合的一条记录；`files` 可展开到单文件状态。
 */
export type AgentToolTargetStatusDto = { tool: Tool; directoryPath: string | null; aggregateStatus: SyncStatus;
/**
 * 工具能力/策略层诊断；文件级漂移诊断仍位于 `files`。
 */
diagnosticCode: string | null; files: AgentFileTargetStatusDto[] }
/**
 * 只有构造函数能写入 details，确保 allowlist 与统一脱敏无法被绕过。
 */
export type AppError = { code: ErrorCode; message: string; details?: Partial<{ [key in string]: JsonValue }> | null; recoverable: boolean; action?: RecoveryAction | null }
export type AppInfoDto = { name: string; version: string }
export type AppSettingsDto = { applyMode: ApplyMode; enabledTools: Tool[] }
export type ApplyAgentPreviewInput = { previewId: string; tool: Tool; projectId: string | null }
export type ApplyHookPreviewInput = { previewId: string; tool: Tool; projectId: string | null }
export type ApplyMcpPreviewInput = { previewId: string; tool: Tool; projectId: string | null }
/**
 * 原生配置写入方式：默认保持预览确认，`Direct` 在预览无冲突时跳过确认对话框。
 */
export type ApplyMode = "preview_confirm" | "direct"
export type ApplyProfilePreviewInput = { previewId: string; tool: Tool; artifactKind: ArtifactKind }
export type ApplyProjectNativeResourcePreviewInput = { previewId: string }
export type ApplyResult = { runId: string; status: string; appliedTargets: number; snapshotCount: number }
export type ApplySkillPreviewInput = { previewId: string; tool: Tool; projectId: string | null }
export type ApplySnapshotRestoreInput = { previewId: string; snapshotId: string }
/**
 * 受管资源种类。
 */
export type ArtifactKind = "provider" | "prompt" | "mcp" | "skill" | "hook" | "agent"
export type CapabilityState = "supported" | "unsupported" | "tool_not_installed"
/**
 * 预览中的单目标变化。
 */
export type ChangeKind = "add" | "update" | "delete" | "unchanged" | "warning" | "conflict"
/**
 * Claude 官方允许的 agent 颜色。
 */
export type ClaudeAgentColor = "red" | "blue" | "green" | "yellow" | "purple" | "orange" | "pink" | "cyan"
/**
 * Claude frontmatter 的首期工具特有设置白名单。
 */
export type ClaudeAgentSettings = { model?: string | null; color?: ClaudeAgentColor | null; tools?: string[] | null }
export type ClaudeCredentialEnvKey = "ANTHROPIC_API_KEY" | "ANTHROPIC_AUTH_TOKEN"
/**
 * Codex agent 的首期工具特有设置白名单。
 */
export type CodexAgentSettings = { model?: string | null; modelReasoningEffort?: CodexReasoningEffort | null; features?: Partial<{ [key in string]: boolean }> | null }
/**
 * Codex 自定义 agent 支持的 reasoning effort。
 */
export type CodexReasoningEffort = "low" | "medium" | "high" | "xhigh" | "max" | "ultra"
export type CompleteOnboardingResultDto = { completed: boolean }
export type ConfirmAgentImportAgent = { definition: CreateAgentInput; toolSettings: JsonValue | null }
/**
 * 用户显式确认导入的条目；服务端只做中央校验，不引用持久化预览，
 * 不改写原生文件；首次分配时若交集字段仍一致则自动登记当前基线。
 */
export type ConfirmAgentImportInput = { tool: Tool; agents: ConfirmAgentImportAgent[] }
/**
 * 用户显式确认导入的条目；服务端只做中央校验，不引用持久化预览。
 */
export type ConfirmHookImportInput = { tool: Tool; hooks: CreateHookInput[] }
export type ConfirmImportInput = { previewId: string; name: string }
export type ConfirmMcpImportInput = { previewId: string; candidateIds: string[] }
export type ConfirmSkillImportInput = { previewId: string; candidateIds: string[] }
export type CopyProviderProfileInput = { sourceId: string; targetTool: Tool; targetName: string; activate: boolean }
export type CreateAgentInput = { name: string; description: string; prompt: string; enabled: boolean }
/**
 * 导入接管时 `script_source_path` 为原脚本绝对路径，服务端会二次校验并
 * 复制到中央目录；手动新增（无脚本接管）传 NULL。
 */
export type CreateHookInput = { name: string; event: HookEvent; matcher: string | null; command: string; timeoutSeconds: number | null; enabled: boolean; scriptSourcePath: string | null }
export type DashboardSummaryDto = { tools: DashboardToolSummaryDto[]; projectCount: number; conflictCount: number; snapshotCount: number; recentSyncRuns: RecentSyncRunDto[]; interruptedRun: InterruptedRunPlan | null; needsOnboarding: boolean }
export type DashboardToolSummaryDto = { tool: Tool; activeProviderName: string | null; activePromptName: string | null; globalMcpCount: number; globalSkillCount: number }
export type DatabaseEntityType = "provider_profile" | "prompt_profile" | "mcp_server" | "skill" | "hook" | "agent" | "project" | "managed_target" | "managed_item" | "project_native_resource"
export type DatabaseRowVersion = { entityType: DatabaseEntityType; entityId: string; rowVersion: number }
export type DeleteAgentResultDto = { id: string; deleted: boolean }
export type DeleteHookResultDto = { id: string; deleted: boolean }
export type DeleteMcpResultDto = { id: string; deleted: boolean }
export type DeleteProfileResultDto = { id: string; deleted: boolean }
export type DeleteSkillResultDto = { id: string; deleted: boolean }
export type DeleteSnapshotsInput = { snapshotIds: string[] }
export type DeleteSnapshotsResultDto = { deletedIds: string[]; failures: SnapshotDeleteFailureDto[] }
export type DiscoverAgentImportInput = { tool: Tool }
export type DiscoverHookImportInput = { tool: Tool }
/**
 * 前端可读的环境探测状态：`probing == true` 时 `tools` 为空。
 */
export type EnvironmentStateDto = { probing: boolean; tools: ToolInstallationDto[] }
/**
 * RPC、journal 和同步记录共用的稳定错误码。
 */
export type ErrorCode = "NOT_FOUND" | "INVALID_INPUT" | "PARSE_ERROR" | "PERMISSION_DENIED" | "POLICY_BLOCKED" | "UNTRUSTED_PROJECT" | "CONFLICT" | "STALE_PREVIEW" | "PREVIEW_ALREADY_CONSUMED" | "WRITE_IN_PROGRESS" | "ATOMIC_WRITE_FAILED" | "ROLLBACK_FAILED" | "SECRET_REDACTED" | "DATABASE_ERROR" | "MIGRATION_FAILED" | "PERMISSION_AUDIT_FAILED" |
/**
 * 工具环境仍在后台探测；只出现在命令边界，永不写入 sync_runs.error_code。
 */
"ENVIRONMENT_PROBING"
export type GitPathStatus = { isRepository: boolean; tracked: boolean; ignored: boolean; ignoredByLocalExclude: boolean }
export type GitRepositoryStatus = "repository" | "not_repository" | "unavailable"
export type HookDto = { id: string; name: string; event: HookEvent; matcher: string | null; command: string; timeoutSeconds: number | null; enabled: boolean; scriptName: string | null; globalAssignments: HookGlobalAssignmentDto[]; rowVersion: number }
/**
 * Hook 的统一事件名（canonical PascalCase）。各工具的原生键可能不同
 * （Cursor 为 camelCase），写入原生文件前必须经
 * [`HookEvent::native_key`] 转换；每工具支持的官方事件集合由
 * [`HookEvent::supported_for_tool`] 定义，不支持的组合必须 fail closed。
 */
export type HookEvent = "SessionStart" | "SessionEnd" | "UserPromptSubmit" | "PreToolUse" | "PermissionRequest" | "PostToolUse" | "PostToolUseFailure" | "SubagentStart" | "SubagentStop" | "PreCompact" | "PostCompact" | "Stop" | "Notification"
/**
 * 由后端事件支持矩阵导出的、供前端过滤选择器的单条能力记录。
 */
export type HookEventSupport = { tool: Tool; event: HookEvent }
/**
 * 全局分配上的生效事件（可因工具而异）。
 */
export type HookGlobalAssignmentDto = { tool: Tool; event: HookEvent }
/**
 * `script_adopted` 表示找到了可接管的原生脚本，确认后脚本本体复制到
 * 中央目录；`script_source_path` 仅在接管时存在。
 */
export type HookImportCandidateDto = { candidateId: string; name: string; event: HookEvent | null; matcher: string | null; command: string; timeoutSeconds: number | null; status: HookImportCandidateStatus; scriptAdopted: boolean; scriptSourcePath: string | null; reason: string | null }
export type HookImportCandidateStatus = "importable" | "already_managed" | "name_conflict" | "unsupported_event" | "invalid"
export type HookImportPreviewDto = { tool: Tool; targetPath: string; candidates: HookImportCandidateDto[]; message: string | null }
export type HookImportResultDto = { tool: Tool; createdCount: number }
export type HookProjectDto = { id: string; displayName: string; rootPath: string; codexTrustStatus: TrustStatus; rowVersion: number }
/**
 * `event` 为中央建议事件（分配预选默认值）；`assigned_event` 仅在
 * state=selected 时存在，为项目分配行上的生效事件。
 */
export type HookProjectOptionDto = { hookId: string; name: string; event: HookEvent; enabled: boolean; state: HookProjectSelectionState; selectable: boolean; assignedEvent: HookEvent | null; rowVersion: number }
export type HookProjectOptionsInput = { projectId: string; tool: Tool }
export type HookProjectSelectionState = "inherited" | "selected" | "available"
export type HookTargetStatusDto = { tool: Tool; projectId: string | null; targetPath: string | null; status: SyncStatus; diagnosticCode: string | null }
export type ImportGithubSkillInput = { url: string }
export type ImportSkillInput = { sourcePath: string }
export type InterruptedRunPlan = { runId: string; status: string; journalAvailable: boolean; targets: InterruptedTargetPlan[] }
export type InterruptedTargetPlan = { targetId: string; targetPath: string; snapshotId: string | null; phase: string; currentType: TargetType | null; currentFingerprint: string | null; errorCode: ErrorCode | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type ManagedOwnership = { kind: "whole_document" } | { kind: "selectors"; paths: string[][] } | { kind: "symlink_names"; paths: string[] }
/**
 * MCP、Skills 与 Hooks 共用的项目选择状态；各 RPC 模块保留历史别名。
 */
export type ManagedProjectSelectionState = "inherited" | "selected" | "available"
export type McpImportAction = "create" | "reuse"
export type McpImportCandidateDto = { candidateId: string; name: string; transport: McpTransport | null; status: McpImportCandidateStatus; action: McpImportAction | null; reason: string | null; redactedProjection: JsonValue }
export type McpImportCandidateStatus = "importable" | "already_managed" | "name_conflict" | "disabled" | "unsupported" | "invalid"
export type McpImportPreviewDto = { previewId: string | null; tool: Tool; targetPath: string; candidates: McpImportCandidateDto[]; message: string | null }
export type McpImportResultDto = { tool: Tool; createdCount: number; reusedCount: number; assignedCount: number }
export type McpProjectDto = { id: string; displayName: string; rootPath: string; codexTrustStatus: TrustStatus; rowVersion: number }
export type McpProjectOptionDto = { mcpId: string; name: string; enabled: boolean; state: McpProjectSelectionState; selectable: boolean; rowVersion: number }
export type McpProjectOptionsInput = { projectId: string; tool: Tool }
export type McpProjectSelectionState = "inherited" | "selected" | "available"
export type McpServerDto = { id: string; name: string; transport: McpTransport; command: string | null; args: string[]; url: string | null; headerNames: string[]; envNames: string[]; redactedExtra: JsonValue; enabled: boolean; globalTools: Tool[]; rowVersion: number }
export type McpServerInput = { name: string; transport: McpTransport; command: string | null; args: string[]; url: string | null; headers: Partial<{ [key in string]: string }>; env: Partial<{ [key in string]: string }>; extra: JsonValue; enabled: boolean }
export type McpTargetStatusDto = { tool: Tool; projectId: string | null; targetPath: string | null; status: SyncStatus; diagnosticCode: string | null }
export type McpTransport = "stdio" | "streamable_http"
export type OfficialLoginPhase =
/**
 * 没有进行中或刚结束的登录会话。
 */
"idle" | "running" | "succeeded" | "failed" | "cancelled" | "timed_out"
export type OfficialLoginStatusDto = { tool: Tool;
/**
 * 官方 CLI 已解析到且提供登录子命令；为 `false` 时只能按 `manual_command` 手动登录。
 */
supported: boolean; phase: OfficialLoginPhase;
/**
 * `None` 表示状态探测不可用（CLI 未安装、超时或输出无法识别）。
 */
loggedIn: boolean | null;
/**
 * CLI 报告的登录方式，如 `claude.ai`、`console`、`chatgpt`、`api_key`。
 */
authMethod: string | null;
/**
 * CLI 报告的账号标识（邮箱或组织名）；只展示，不落库不写日志。
 */
account: string | null;
/**
 * 最近一次登录子进程或状态探测的脱敏诊断片段。
 */
diagnostic: string | null;
/**
 * 登录子进程打印的授权地址；浏览器没有自动打开时供用户手动访问。
 */
loginUrl: string | null; manualCommand: string }
export type PolicyState = "allowed" | "blocked" | "unknown"
export type PrepareSkillTakeoverInput = { previewId: string; candidateIds: string[] }
export type PreviewAgentSyncInput = { tool: Tool; projectId: string | null; excludeFromGit: boolean }
export type PreviewHookSyncInput = { tool: Tool; projectId: string | null; excludeFromGit: boolean }
export type PreviewMcpSyncInput = { tool: Tool; projectId: string | null; excludeFromGit: boolean }
export type PreviewPlan = { previewId: string; scope: Scope; projectId: string | null; dbVersion: number; targets: PreviewTargetPlan[]; warningCodes: string[] }
export type PreviewProjectNativeResourceActionInput = { resourceId: string; rowVersion: number; action: ProjectNativeResourceAction }
export type PreviewSkillSyncInput = { tool: Tool; projectId: string | null; excludeFromGit: boolean }
export type PreviewTargetPlan = { targetId: string; descriptor: TargetDescriptor; ownership: ManagedOwnership; changeKind: ChangeKind; status: SyncStatus; currentFullHash: string | null; currentManagedHash: string | null; desiredManagedHash: string; targetRowVersion: number; rowVersions: DatabaseRowVersion[]; redactedDiff: JsonValue; warningCodes: string[]; baselineMismatchedItems: string[]; readoptAvailable: boolean; errorCode: ErrorCode | null; git: GitPathStatus | null; excludeFromGit: boolean }
export type ProjectDto = { id: string; displayName: string; rootPath: string; pathStatus: ProjectPathStatus; gitStatus: GitRepositoryStatus; codexTrustStatus: TrustStatus; claudePolicyStatus: PolicyState; targets: ProjectTargetStatusDto[]; nativeResources: ProjectNativeResourceSummaryDto; lastScannedAt: string | null; rowVersion: number }
export type ProjectNativeEntryType = "mcp_entry" | "directory" | "symlink" | "hook_entry" | "agent_file"
export type ProjectNativeResourceAction = "disable" | "restore"
export type ProjectNativeResourceDto = { id: string; projectId: string; tool: Tool; artifactKind: ArtifactKind; displayName: string; targetPath: string; entryType: ProjectNativeEntryType; state: ProjectNativeResourceState; rowVersion: number; canDisable: boolean; canRestore: boolean; diagnosticCodes: string[]; safeSummary: JsonValue; disabledAt: string | null }
export type ProjectNativeResourceKind = "mcp" | "skill"
export type ProjectNativeResourceQueryInput = { projectId: string; tool: Tool; artifactKind: ArtifactKind }
export type ProjectNativeResourceState = "active" | "disabled" | "missing" | "conflict"
export type ProjectNativeResourceSummaryDto = { active: number; disabled: number; missing: number; conflict: number }
export type ProjectPathStatus = "valid" | "missing" | "permission_denied" | "invalid"
export type ProjectTargetStatusDto = { tool: Tool; artifactKind: ArtifactKind; targetPath: string | null; capability: CapabilityState; policy: PolicyState; trust: TargetTrustState; status: SyncStatus; diagnosticCode: string | null }
export type PromptImportPreviewDto = { previewId: string; tool: Tool; targetPath: string; suggestedName: string; body: string }
export type PromptOverrideState = "not_applicable" | "not_present" | "present" | "unknown"
export type PromptProfileDto = { id: string; name: string; body: string; globalTools: Tool[]; importedFromPath: string | null; rowVersion: number }
export type PromptProfileInput = { name: string; body: string }
/**
 * 渠道的认证方式：`ApiKey` 走第三方/自定义接入地址加密钥；`OfficialLogin`
 * 不保存任何接入地址或密钥，原生配置回到工具自带的官方账号登录。
 */
export type ProviderAuthKind = "api_key" | "official_login"
export type ProviderImportPreviewDto = { previewId: string; tool: Tool; targetPath: string; suggestedName: string; authKind: ProviderAuthKind; apiBaseUrl: string; apiKeyConfigured: boolean; defaultModel: string; redactedProjection: JsonValue;
/**
 * 原生 env 中疑似凭据或格式不受支持、因此未纳入管理的键名（不含值）。
 */
skippedEnvKeys: string[] }
export type ProviderOptionsDto = { authKind: ProviderAuthKind; credentialEnvKey: ClaudeCredentialEnvKey | null; extraEnv: Partial<{ [key in string]: string }>; providerId: string | null; wireApi: string | null; zcodeKind: string | null; opencodeNpm: string | null; opencodeApi: string | null }
export type ProviderOptionsInput = {
/**
 * 旧前端不传时默认 `api_key`；创建后不可更改。
 */
authKind?: ProviderAuthKind; credentialEnvKey: ClaudeCredentialEnvKey | null; extraEnv: Partial<{ [key in string]: string }>; wireApi: string | null; zcodeKind: string | null;
/**
 * OpenCode provider SDK package (for example
 * `@ai-sdk/openai-compatible`). Stored as metadata; the app never
 * installs or executes the package.
 */
opencodeNpm: string | null; opencodeApi: string | null }
export type ProviderProfileDto = { id: string; tool: Tool; name: string; apiBaseUrl: string; apiKeyConfigured: boolean; defaultModel: string; options: ProviderOptionsDto; isActive: boolean; rowVersion: number }
export type ProviderProfileInput = { tool: Tool; name: string; apiBaseUrl: string; apiKey: string; defaultModel: string; options: ProviderOptionsInput; activate: boolean }
export type ReadoptAgentTargetInput = { tool: Tool; projectId: string | null; targetPath: string }
export type ReadoptAgentTargetResultDto = { targetPath: string }
export type ReadoptHookTargetInput = { tool: Tool; projectId: string | null }
export type ReadoptHookTargetResultDto = { targetPath: string; updatedItemCount: number; removedItemCount: number }
export type ReadoptMcpTargetInput = { tool: Tool; projectId: string | null }
export type ReadoptMcpTargetResultDto = { targetPath: string; updatedItemCount: number; removedItemCount: number }
export type RecentSyncRunDto = { id: string; kind: SyncRunKind; status: SyncRunStatus; scope: Scope; projectId: string | null; startedAt: string; finishedAt: string | null; errorCode: ErrorCode | null }
export type RecoveryAction = "rescan" | "review_conflict" | "restore" | "fix_permissions"
export type RegisterProjectInput = { displayName: string; rootPath: string }
export type RemoveProjectResultDto = { id: string; removed: boolean; nativeConfigurationLeftUnmanaged: boolean }
export type RenameProjectInput = { id: string; displayName: string; rowVersion: number }
export type RestorePreview = { previewId: string; snapshotId: string; targetPath: string; currentType: TargetType; snapshotType: TargetType; storageKind: SnapshotStorageKind }
/**
 * 资源应用范围。
 */
export type Scope = "global" | "project"
export type SecretUpdate = { action: "keep" } | { action: "clear" } | { action: "replace"; value: string }
export type SensitiveJsonUpdate = { action: "keep" } | { action: "clear" } | { action: "replace"; value: JsonValue }
export type SensitiveMapUpdate = { action: "keep" } | { action: "clear" } | { action: "replace"; value: Partial<{ [key in string]: string }> }
export type SetAgentToolSettingsInput = { agentId: string; tool: Tool; settings: JsonValue | null; rowVersion: number }
export type SetGlobalAgentAssignmentInput = { tool: Tool; agentId: string; assigned: boolean; rowVersion: number }
/**
 * 分配时 `event` 为生效事件（可不同于中央建议事件）；取消分配时忽略。
 * 同一 (tool, hook) 已分配时传入不同 event 即切换事件。
 */
export type SetGlobalHookAssignmentInput = { tool: Tool; hookId: string; event: HookEvent; assigned: boolean; rowVersion: number }
export type SetGlobalMcpAssignmentInput = { tool: Tool; mcpId: string; assigned: boolean; rowVersion: number }
/**
 * 全局启用/停用一份提示词档案到指定工具；每工具至多一份生效，
 * 启用新档案会自动替换该工具的原生效档案。
 */
export type SetGlobalPromptAssignmentInput = { tool: Tool; promptProfileId: string; assigned: boolean; rowVersion: number }
export type SetGlobalSkillAssignmentInput = { tool: Tool; skillId: string; assigned: boolean; rowVersion: number }
export type SetProjectAgentAssignmentInput = { projectId: string; tool: Tool; agentId: string; assigned: boolean; agentRowVersion: number; projectRowVersion: number }
/**
 * 事件语义同全局分配（随分配存储，可切换）。
 */
export type SetProjectHookAssignmentInput = { projectId: string; tool: Tool; hookId: string; event: HookEvent; assigned: boolean; hookRowVersion: number; projectRowVersion: number }
export type SetProjectMcpAssignmentInput = { projectId: string; tool: Tool; mcpId: string; assigned: boolean; mcpRowVersion: number; projectRowVersion: number }
export type SetProjectSkillAssignmentInput = { projectId: string; tool: Tool; skillId: string; assigned: boolean; skillRowVersion: number; projectRowVersion: number }
export type SkillContentPreviewDto = { id: string; name: string; skillMd: string; files: string[]; contentHash: string; rowVersion: number }
export type SkillDto = { id: string; name: string; sourcePath: string; centralPath: string; contentHash: string; description: string; status: SkillStatus; diagnosticCode: string | null; globalTools: Tool[]; rowVersion: number }
export type SkillImportCandidateDto = { candidateId: string; name: string; description: string; sourcePaths: string[]; status: SkillImportCandidateStatus; reason: string | null; existingSkillId: string | null; takeoverEligible: boolean; takeoverEntryType: SkillTakeoverEntryType | null }
export type SkillImportCandidateStatus = "importable" | "already_imported" | "name_conflict" | "invalid"
export type SkillImportPreviewDto = { previewId: string | null; tool: Tool; sources: SkillImportSourceDto[]; candidates: SkillImportCandidateDto[]; message: string | null }
export type SkillImportResultDto = { tool: Tool; createdCount: number }
export type SkillImportSourceDto = { kind: SkillImportSourceKind; path: string; status: SkillImportSourceStatus; diagnosticCode: string | null; message: string | null }
export type SkillImportSourceKind = "claude_global" | "codex_home" | "codex_agents" | "cursor_home" | "cursor_agents" | "zcode_home" | "zcode_agents" | "opencode_global"
export type SkillImportSourceStatus = "ready" | "missing" | "empty" | "unavailable"
export type SkillProjectDto = { id: string; displayName: string; rootPath: string; codexTrustStatus: TrustStatus; rowVersion: number }
export type SkillProjectOptionDto = { skillId: string; name: string; status: SkillStatus; state: SkillProjectSelectionState; selectable: boolean; rowVersion: number }
export type SkillProjectOptionsInput = { projectId: string; tool: Tool }
export type SkillProjectSelectionState = "inherited" | "selected" | "available"
export type SkillStatus = "ready" | "invalid" | "missing"
export type SkillTakeoverEntryType = "external_symlink" | "directory"
export type SkillTakeoverPreviewResultDto = { tool: Tool; assignedCount: number; reusedCount: number; plan: PreviewPlan }
export type SkillTargetStatusDto = { tool: Tool; projectId: string | null; targetPath: string | null; status: SyncStatus; diagnosticCode: string | null }
export type SnapshotDeleteFailureDto = { snapshotId: string; code: string; message: string }
export type SnapshotRestoreInput = { snapshotId: string }
export type SnapshotStorageKind = "payload_file" | "metadata_only" | "directory_tree"
export type SnapshotSummary = { snapshotId: string; runId: string; targetId: string | null; targetPath: string; targetType: TargetType; storageKind: SnapshotStorageKind; restorable: boolean; createdAt: string }
export type SymlinkPolicy = "reject" | "managed_children_only"
export type SyncRunKind = "preview" | "apply" | "restore"
export type SyncRunStatus = "previewed" | "applying" | "restoring" | "succeeded" | "failed" | "stale" | "rolled_back" | "rollback_failed"
/**
 * 原生目标相对最近一次受管基线的状态。
 */
export type SyncStatus = "in_sync" | "external_non_owned_change" | "external_owned_change" | "missing" | "parse_error" | "permission_denied" | "policy_blocked" | "untrusted" | "target_type_changed" | "failed"
export type TargetCapability = { state: CapabilityState; diagnosticCode: string | null }
/**
 * Adapter 对一个原生目标的完整只读合同。
 */
export type TargetDescriptor = { tool: Tool; artifactKind: ArtifactKind; scope: Scope; projectRoot: string | null; path: string | null;
/**
 * 外部写入安全边界；Global 目标由 Adapter 显式提供，Project 目标通常等于 project_root。
 */
allowedRoot: string | null;
/**
 * MCP 受管投影所在的原生容器路径。
 */
mcpContainer: string[] | null; format: TargetFormat; managedSelectorRoots: string[]; sensitiveSelectors: string[]; capability: TargetCapability; policy: PolicyState; trust: TargetTrustState; promptOverride: PromptOverrideState; symlinkPolicy: SymlinkPolicy }
export type TargetFormat = "json" |
/**
 * OpenCode's JSON with comments/trailing commas. The parser keeps the
 * original source so managed top-level replacements do not discard
 * unrelated comments and keys.
 */
"jsonc" | "toml" | "markdown" |
/**
 * Cursor 规则文件（`.cursor/rules/*.mdc`）：Markdown + 固定
 * `alwaysApply: true` frontmatter。渲染时包装、观测时剥离，
 * 受管投影域与其他工具的纯 Markdown 正文保持同构。
 */
"cursor_mdc" | "symlink_directory"
export type TargetTrustState = "not_required" | "trusted" | "untrusted" | "unknown"
export type TargetType = "file" | "directory" | "symlink" | "missing"
/**
 * 正式支持的原生工具。
 */
export type Tool = "claude" | "codex" | "cursor" | "zcode" | "opencode"
export type ToolAvailabilityState = "installed" | "unavailable" | "unsupported"
/**
 * 前端需要展示和过滤的工具能力。
 *
 * 该结构是能力矩阵的唯一跨层来源；展示标签、图标和路由仍属于前端，
 * 但哪些工具支持哪类受管资源必须由领域层决定。
 */
export type ToolCapabilities = { tool: Tool; provider: boolean; promptGlobal: boolean; mcp: boolean; skills: boolean; hooks: boolean;
/**
 * Agents（子代理）全局级管理：五工具均支持（ZCode 为官方 Beta，仍可用）。
 */
agents: boolean;
/**
 * Agents 项目级管理：ZCode 官方明示不支持，其余四工具支持。
 */
projectAgents: boolean;
/**
 * Agent 工具特有设置覆盖层：首期仅 Claude / Codex 有白名单合同。
 */
agentToolSettings: boolean }
export type ToolInstallationDto = { tool: Tool; availability: ToolAvailabilityState; installationVersion: string | null; installationProbeDiagnostic: string | null }
export type ToolProfileStatusDto = { tool: Tool; availability: ToolAvailabilityState; installationVersion: string | null;
/**
 * 安装探针的稳定诊断码；解释探测为何是当前状态（如 PATH 条目被跳过）。
 */
installationProbeDiagnostic: string | null; providerTargetPath: string | null; promptTargetPath: string | null; providerCapability: TargetCapability; promptCapability: TargetCapability; promptOverride: PromptOverrideState; providerPolicy: PolicyState; newSessionNotice: string; bearerTokenWarning: string | null }
export type TrustStatus = "unknown" | "trusted" | "untrusted"
export type UpdateAgentInput = { id: string; name: string; description: string; prompt: string; enabled: boolean; rowVersion: number }
export type UpdateAppSettingsInput = { applyMode: ApplyMode; enabledTools: Tool[] }
export type UpdateHookInput = { id: string; name: string; event: HookEvent; matcher: string | null; command: string; timeoutSeconds: number | null; enabled: boolean; rowVersion: number }
export type UpdateMcpServerInput = { id: string; name: string; transport: McpTransport; command: string | null; args: string[]; url: string | null; headers: SensitiveMapUpdate; env: SensitiveMapUpdate; extra: SensitiveJsonUpdate; enabled: boolean; rowVersion: number }
export type UpdatePromptProfileInput = { id: string; name: string; body: string; rowVersion: number }
export type UpdateProviderProfileInput = { id: string; name: string; apiBaseUrl: string; apiKey: SecretUpdate; defaultModel: string; options: ProviderOptionsInput; rowVersion: number }
export type VersionedAgentInput = { id: string; rowVersion: number }
export type VersionedHookInput = { id: string; rowVersion: number }
export type VersionedMcpInput = { id: string; rowVersion: number }
export type VersionedProfileInput = { id: string; rowVersion: number }
export type VersionedProjectInput = { id: string; rowVersion: number }
export type VersionedSkillInput = { id: string; rowVersion: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
