
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAppInfo() : Promise<AppInfoDto> {
    return await TAURI_INVOKE("get_app_info");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * 只有构造函数能写入 details，确保 allowlist 与统一脱敏无法被绕过。
 */
export type AppError = { code: ErrorCode; message: string; details?: Partial<{ [key in string]: JsonValue }> | null; recoverable: boolean; action?: RecoveryAction | null }
export type AppInfoDto = { name: string; version: string }
/**
 * 受管资源种类。
 */
export type ArtifactKind = "provider" | "prompt" | "mcp" | "skill"
export type CapabilityState = "supported" | "unsupported" | "tool_not_installed"
/**
 * 预览中的单目标变化。
 */
export type ChangeKind = "add" | "update" | "delete" | "unchanged" | "warning" | "conflict"
export type DatabaseEntityType = "provider_profile" | "prompt_profile" | "mcp_server" | "skill" | "project" | "managed_target" | "managed_item"
export type DatabaseRowVersion = { entityType: DatabaseEntityType; entityId: string; rowVersion: number }
/**
 * RPC、journal 和同步记录共用的稳定错误码。
 */
export type ErrorCode = "NOT_FOUND" | "INVALID_INPUT" | "PARSE_ERROR" | "PERMISSION_DENIED" | "POLICY_BLOCKED" | "UNTRUSTED_PROJECT" | "CONFLICT" | "STALE_PREVIEW" | "PREVIEW_ALREADY_CONSUMED" | "WRITE_IN_PROGRESS" | "ATOMIC_WRITE_FAILED" | "ROLLBACK_FAILED" | "SECRET_REDACTED" | "DATABASE_ERROR" | "MIGRATION_FAILED" | "PERMISSION_AUDIT_FAILED"
export type GitPathStatus = { isRepository: boolean; tracked: boolean; ignored: boolean; ignoredByLocalExclude: boolean }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type McpTransport = "stdio" | "streamable_http"
export type PolicyState = "allowed" | "blocked" | "unknown"
export type PreviewPlan = { previewId: string; scope: Scope; projectId: string | null; dbVersion: number; targets: PreviewTargetPlan[]; warningCodes: string[] }
export type PreviewTargetPlan = { targetId: string; descriptor: TargetDescriptor; changeKind: ChangeKind; status: SyncStatus; currentFullHash: string | null; currentManagedHash: string | null; targetRowVersion: number; rowVersions: DatabaseRowVersion[]; redactedDiff: JsonValue; warningCodes: string[]; errorCode: ErrorCode | null; git: GitPathStatus | null }
export type PromptOverrideState = "not_applicable" | "not_present" | "present" | "unknown"
export type RecoveryAction = "rescan" | "review_conflict" | "restore" | "fix_permissions"
/**
 * 资源应用范围。
 */
export type Scope = "global" | "project"
export type SkillStatus = "ready" | "invalid" | "missing"
export type SymlinkPolicy = "reject" | "managed_children_only"
export type SyncRunKind = "preview" | "apply" | "restore"
export type SyncRunStatus = "previewed" | "applying" | "restoring" | "succeeded" | "failed" | "stale" | "rolled_back" | "rollback_failed"
/**
 * 原生目标相对最近一次受管基线的状态。
 */
export type SyncStatus = "in_sync" | "external_non_owned_change" | "external_owned_change" | "missing" | "parse_error" | "permission_denied" | "policy_blocked" | "untrusted" | "target_type_changed" | "failed"
export type TargetCapability = { state: CapabilityState; diagnosticCode: string | null }
/**
 * Adapter 对一个原生目标的完整只读合同。
 */
export type TargetDescriptor = { tool: Tool; artifactKind: ArtifactKind; scope: Scope; projectRoot: string | null; path: string | null; format: TargetFormat; managedSelectorRoots: string[]; sensitiveSelectors: string[]; capability: TargetCapability; policy: PolicyState; trust: TargetTrustState; promptOverride: PromptOverrideState; symlinkPolicy: SymlinkPolicy }
export type TargetFormat = "json" | "toml" | "markdown" | "symlink_directory"
export type TargetTrustState = "not_required" | "trusted" | "untrusted" | "unknown"
export type TargetType = "file" | "directory" | "symlink" | "missing"
/**
 * 正式支持的原生工具。
 */
export type Tool = "claude" | "codex"
export type TrustStatus = "unknown" | "trusted" | "untrusted"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
