
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAppInfo() : Promise<AppInfoDto> {
    return await TAURI_INVOKE("get_app_info");
},
async getDashboardSummary() : Promise<Result<DashboardSummaryDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dashboard_summary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async completeOnboarding() : Promise<Result<CompleteOnboardingResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_onboarding") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSnapshots() : Promise<Result<SnapshotSummary[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_snapshots") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSnapshots(input: DeleteSnapshotsInput) : Promise<Result<DeleteSnapshotsResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_snapshots", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInterruptedRun() : Promise<Result<InterruptedRunPlan | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_interrupted_run") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewSnapshotRestore(input: SnapshotRestoreInput) : Promise<Result<RestorePreview, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_snapshot_restore", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreSnapshot(input: ApplySnapshotRestoreInput) : Promise<Result<ApplyResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_snapshot", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettingsDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAppSettings(input: UpdateAppSettingsInput) : Promise<Result<AppSettingsDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_app_settings", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProjects() : Promise<Result<ProjectDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProject(id: string) : Promise<Result<ProjectDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async registerProject(input: RegisterProjectInput) : Promise<Result<ProjectDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_project", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rescanProject(input: VersionedProjectInput) : Promise<Result<ProjectDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rescan_project", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeProject(input: VersionedProjectInput) : Promise<Result<RemoveProjectResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_project", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProviderProfiles(tool: Tool) : Promise<Result<ProviderProfileDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_provider_profiles", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createProviderProfile(input: ProviderProfileInput) : Promise<Result<ProviderProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_provider_profile", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateProviderProfile(input: UpdateProviderProfileInput) : Promise<Result<ProviderProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_provider_profile", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async copyProviderProfile(input: CopyProviderProfileInput) : Promise<Result<ProviderProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_provider_profile", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveProviderProfile(tool: Tool, input: VersionedProfileInput) : Promise<Result<ProviderProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_provider_profile", { tool, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteProviderProfile(input: VersionedProfileInput) : Promise<Result<DeleteProfileResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_provider_profile", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPromptProfiles() : Promise<Result<PromptProfileDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_prompt_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createPromptProfile(input: PromptProfileInput) : Promise<Result<PromptProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_prompt_profile", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePromptProfile(input: UpdatePromptProfileInput) : Promise<Result<PromptProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_prompt_profile", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGlobalPromptAssignment(input: SetGlobalPromptAssignmentInput) : Promise<Result<PromptProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_global_prompt_assignment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePromptProfile(input: VersionedProfileInput) : Promise<Result<DeleteProfileResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_prompt_profile", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getToolProfileStatus(tool: Tool) : Promise<Result<ToolProfileStatusDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tool_profile_status", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverProviderImport(tool: Tool) : Promise<Result<ProviderImportPreviewDto | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_provider_import", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async confirmProviderImport(input: ConfirmImportInput) : Promise<Result<ProviderProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_provider_import", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverPromptImport(tool: Tool) : Promise<Result<PromptImportPreviewDto | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_prompt_import", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async confirmPromptImport(input: ConfirmImportInput) : Promise<Result<PromptProfileDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_prompt_import", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewProviderSync(tool: Tool) : Promise<Result<PreviewPlan, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_provider_sync", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewPromptSync(tool: Tool, projectId: string | null) : Promise<Result<PreviewPlan, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_prompt_sync", { tool, projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPromptProjectAssignment(input: SetPromptProjectAssignmentInput) : Promise<Result<PromptProjectAssignmentDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_prompt_project_assignment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPromptProjectAssignment(projectId: string, tool: Tool) : Promise<Result<PromptProjectAssignmentDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_prompt_project_assignment", { projectId, tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyProfilePreview(input: ApplyProfilePreviewInput) : Promise<Result<ApplyResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_profile_preview", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMcpServers() : Promise<Result<McpServerDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_mcp_servers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMcpServer(id: string) : Promise<Result<McpServerDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mcp_server", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createMcpServer(input: McpServerInput) : Promise<Result<McpServerDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_mcp_server", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMcpServer(input: UpdateMcpServerInput) : Promise<Result<McpServerDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_mcp_server", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMcpEnabled(input: VersionedMcpInput, enabled: boolean) : Promise<Result<McpServerDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_mcp_enabled", { input, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMcpServer(input: VersionedMcpInput) : Promise<Result<DeleteMcpResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_mcp_server", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGlobalMcpAssignment(input: SetGlobalMcpAssignmentInput) : Promise<Result<McpServerDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_global_mcp_assignment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setProjectMcpAssignment(input: SetProjectMcpAssignmentInput) : Promise<Result<McpServerDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_project_mcp_assignment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMcpProjects() : Promise<Result<McpProjectDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_mcp_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMcpProjectOptions(input: McpProjectOptionsInput) : Promise<Result<McpProjectOptionDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_mcp_project_options", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGlobalMcpTargetStatuses() : Promise<Result<McpTargetStatusDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_global_mcp_target_statuses") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewMcpSync(input: PreviewMcpSyncInput) : Promise<Result<PreviewPlan, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_mcp_sync", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyMcpPreview(input: ApplyMcpPreviewInput) : Promise<Result<ApplyResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_mcp_preview", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readoptMcpTarget(input: ReadoptMcpTargetInput) : Promise<Result<ReadoptMcpTargetResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("readopt_mcp_target", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverMcpImport(tool: Tool) : Promise<Result<McpImportPreviewDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_mcp_import", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async confirmMcpImport(input: ConfirmMcpImportInput) : Promise<Result<McpImportResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_mcp_import", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkills() : Promise<Result<SkillDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skills") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSkill(id: string) : Promise<Result<SkillDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_skill", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importSkill(input: ImportSkillInput) : Promise<Result<SkillDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_skill", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverSkillImport(tool: Tool) : Promise<Result<SkillImportPreviewDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_skill_import", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async confirmSkillImport(input: ConfirmSkillImportInput) : Promise<Result<SkillImportResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_skill_import", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async prepareSkillTakeover(input: PrepareSkillTakeoverInput) : Promise<Result<SkillTakeoverPreviewResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prepare_skill_takeover", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewSkillContent(id: string) : Promise<Result<SkillContentPreviewDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_skill_content", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSkill(input: VersionedSkillInput) : Promise<Result<DeleteSkillResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_skill", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGlobalSkillAssignment(input: SetGlobalSkillAssignmentInput) : Promise<Result<SkillDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_global_skill_assignment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setProjectSkillAssignment(input: SetProjectSkillAssignmentInput) : Promise<Result<SkillDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_project_skill_assignment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkillProjects() : Promise<Result<SkillProjectDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skill_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkillProjectOptions(input: SkillProjectOptionsInput) : Promise<Result<SkillProjectOptionDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skill_project_options", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGlobalSkillTargetStatuses() : Promise<Result<SkillTargetStatusDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_global_skill_target_statuses") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewSkillSync(input: PreviewSkillSyncInput) : Promise<Result<PreviewPlan, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_skill_sync", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applySkillPreview(input: ApplySkillPreviewInput) : Promise<Result<ApplyResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_skill_preview", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * 只有构造函数能写入 details，确保 allowlist 与统一脱敏无法被绕过。
 */
export type AppError = { code: ErrorCode; message: string; details?: Partial<{ [key in string]: JsonValue }> | null; recoverable: boolean; action?: RecoveryAction | null }
export type AppInfoDto = { name: string; version: string }
export type AppSettingsDto = { applyMode: ApplyMode }
export type ApplyMcpPreviewInput = { previewId: string; tool: Tool; projectId: string | null }
/**
 * 原生配置写入方式：默认保持预览确认，`Direct` 在预览无冲突时跳过确认对话框。
 */
export type ApplyMode = "preview_confirm" | "direct"
export type ApplyProfilePreviewInput = { previewId: string; tool: Tool; artifactKind: ArtifactKind; projectId: string | null }
export type ApplyResult = { runId: string; status: string; appliedTargets: number; snapshotCount: number }
export type ApplySkillPreviewInput = { previewId: string; tool: Tool; projectId: string | null }
export type ApplySnapshotRestoreInput = { previewId: string; snapshotId: string }
/**
 * 受管资源种类。
 */
export type ArtifactKind = "provider" | "prompt" | "mcp" | "skill"
export type CapabilityState = "supported" | "unsupported" | "tool_not_installed"
/**
 * 预览中的单目标变化。
 */
export type ChangeKind = "add" | "update" | "delete" | "unchanged" | "warning" | "conflict"
export type ClaudeCredentialEnvKey = "ANTHROPIC_API_KEY" | "ANTHROPIC_AUTH_TOKEN"
export type CompleteOnboardingResultDto = { completed: boolean }
export type ConfirmImportInput = { previewId: string; name: string }
export type ConfirmMcpImportInput = { previewId: string; candidateIds: string[] }
export type ConfirmSkillImportInput = { previewId: string; candidateIds: string[] }
export type CopyProviderProfileInput = { sourceId: string; targetTool: Tool; targetName: string; activate: boolean }
export type DashboardSummaryDto = { tools: DashboardToolSummaryDto[]; projectCount: number; conflictCount: number; snapshotCount: number; recentSyncRuns: RecentSyncRunDto[]; interruptedRun: InterruptedRunPlan | null; needsOnboarding: boolean }
export type DashboardToolSummaryDto = { tool: Tool; activeProviderName: string | null; activePromptName: string | null; globalMcpCount: number; globalSkillCount: number }
export type DatabaseEntityType = "provider_profile" | "prompt_profile" | "mcp_server" | "skill" | "project" | "managed_target" | "managed_item"
export type DatabaseRowVersion = { entityType: DatabaseEntityType; entityId: string; rowVersion: number }
export type DeleteMcpResultDto = { id: string; deleted: boolean }
export type DeleteProfileResultDto = { id: string; deleted: boolean }
export type DeleteSkillResultDto = { id: string; deleted: boolean }
export type DeleteSnapshotsInput = { snapshotIds: string[] }
export type DeleteSnapshotsResultDto = { deletedIds: string[]; failures: SnapshotDeleteFailureDto[] }
/**
 * RPC、journal 和同步记录共用的稳定错误码。
 */
export type ErrorCode = "NOT_FOUND" | "INVALID_INPUT" | "PARSE_ERROR" | "PERMISSION_DENIED" | "POLICY_BLOCKED" | "UNTRUSTED_PROJECT" | "CONFLICT" | "STALE_PREVIEW" | "PREVIEW_ALREADY_CONSUMED" | "WRITE_IN_PROGRESS" | "ATOMIC_WRITE_FAILED" | "ROLLBACK_FAILED" | "SECRET_REDACTED" | "DATABASE_ERROR" | "MIGRATION_FAILED" | "PERMISSION_AUDIT_FAILED"
export type GitPathStatus = { isRepository: boolean; tracked: boolean; ignored: boolean; ignoredByLocalExclude: boolean }
export type GitRepositoryStatus = "repository" | "not_repository" | "unavailable"
export type ImportSkillInput = { sourcePath: string }
export type InterruptedRunPlan = { runId: string; status: string; journalAvailable: boolean; targets: InterruptedTargetPlan[] }
export type InterruptedTargetPlan = { targetId: string; targetPath: string; snapshotId: string | null; phase: string; currentType: TargetType | null; currentFingerprint: string | null; errorCode: ErrorCode | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type ManagedOwnership = { kind: "whole_document" } | { kind: "selectors"; paths: string[][] } | { kind: "symlink_names"; paths: string[] }
export type McpImportAction = "create" | "reuse"
export type McpImportCandidateDto = { candidateId: string; name: string; transport: McpTransport | null; status: McpImportCandidateStatus; action: McpImportAction | null; reason: string | null; redactedProjection: JsonValue }
export type McpImportCandidateStatus = "importable" | "already_managed" | "name_conflict" | "disabled" | "unsupported" | "invalid"
export type McpImportPreviewDto = { previewId: string | null; tool: Tool; targetPath: string; candidates: McpImportCandidateDto[]; message: string | null }
export type McpImportResultDto = { tool: Tool; createdCount: number; reusedCount: number; assignedCount: number }
export type McpProjectDto = { id: string; displayName: string; rootPath: string; codexTrustStatus: TrustStatus; rowVersion: number }
export type McpProjectOptionDto = { mcpId: string; name: string; enabled: boolean; state: McpProjectSelectionState; selectable: boolean; rowVersion: number }
export type McpProjectOptionsInput = { projectId: string; tool: Tool }
export type McpProjectSelectionState = "inherited" | "selected" | "available"
export type McpServerDto = { id: string; name: string; transport: McpTransport; command: string | null; args: string[]; url: string | null; headerNames: string[]; envNames: string[]; redactedExtra: JsonValue; enabled: boolean; globalTools: Tool[]; rowVersion: number }
export type McpServerInput = { name: string; transport: McpTransport; command: string | null; args: string[]; url: string | null; headers: Partial<{ [key in string]: string }>; env: Partial<{ [key in string]: string }>; extra: JsonValue; enabled: boolean }
export type McpTargetStatusDto = { tool: Tool; projectId: string | null; targetPath: string | null; status: SyncStatus; diagnosticCode: string | null }
export type McpTransport = "stdio" | "streamable_http"
export type PolicyState = "allowed" | "blocked" | "unknown"
export type PrepareSkillTakeoverInput = { previewId: string; candidateIds: string[] }
export type PreviewMcpSyncInput = { tool: Tool; projectId: string | null; excludeFromGit: boolean }
export type PreviewPlan = { previewId: string; scope: Scope; projectId: string | null; dbVersion: number; targets: PreviewTargetPlan[]; warningCodes: string[] }
export type PreviewSkillSyncInput = { tool: Tool; projectId: string | null; excludeFromGit: boolean }
export type PreviewTargetPlan = { targetId: string; descriptor: TargetDescriptor; ownership: ManagedOwnership; changeKind: ChangeKind; status: SyncStatus; currentFullHash: string | null; currentManagedHash: string | null; desiredManagedHash: string; targetRowVersion: number; rowVersions: DatabaseRowVersion[]; redactedDiff: JsonValue; warningCodes: string[]; baselineMismatchedItems: string[]; readoptAvailable: boolean; errorCode: ErrorCode | null; git: GitPathStatus | null; excludeFromGit: boolean }
export type ProjectDto = { id: string; displayName: string; rootPath: string; pathStatus: ProjectPathStatus; gitStatus: GitRepositoryStatus; codexTrustStatus: TrustStatus; claudePolicyStatus: PolicyState; targets: ProjectTargetStatusDto[]; lastScannedAt: string | null; rowVersion: number }
export type ProjectPathStatus = "valid" | "missing" | "permission_denied" | "invalid"
export type ProjectTargetStatusDto = { tool: Tool; artifactKind: ArtifactKind; targetPath: string | null; capability: CapabilityState; policy: PolicyState; trust: TargetTrustState; status: SyncStatus; diagnosticCode: string | null }
export type PromptImportPreviewDto = { previewId: string; tool: Tool; targetPath: string; suggestedName: string; body: string }
export type PromptOverrideState = "not_applicable" | "not_present" | "present" | "unknown"
export type PromptProfileDto = { id: string; name: string; body: string; globalTools: Tool[]; importedFromPath: string | null; rowVersion: number }
export type PromptProfileInput = { name: string; body: string }
export type PromptProjectAssignmentDto = { projectId: string; tool: Tool; profileId: string | null }
export type ProviderImportPreviewDto = { previewId: string; tool: Tool; targetPath: string; suggestedName: string; apiBaseUrl: string; apiKeyConfigured: boolean; defaultModel: string; redactedProjection: JsonValue }
export type ProviderOptionsDto = { credentialEnvKey: ClaudeCredentialEnvKey | null; extraEnv: Partial<{ [key in string]: string }>; providerId: string | null; wireApi: string | null }
export type ProviderOptionsInput = { credentialEnvKey: ClaudeCredentialEnvKey | null; extraEnv: Partial<{ [key in string]: string }>; wireApi: string | null }
export type ProviderProfileDto = { id: string; tool: Tool; name: string; apiBaseUrl: string; apiKeyConfigured: boolean; defaultModel: string; options: ProviderOptionsDto; isActive: boolean; rowVersion: number }
export type ProviderProfileInput = { tool: Tool; name: string; apiBaseUrl: string; apiKey: string; defaultModel: string; options: ProviderOptionsInput; activate: boolean }
export type ReadoptMcpTargetInput = { tool: Tool; projectId: string | null }
export type ReadoptMcpTargetResultDto = { targetPath: string; updatedItemCount: number; removedItemCount: number }
export type RecentSyncRunDto = { id: string; kind: SyncRunKind; status: SyncRunStatus; scope: Scope; projectId: string | null; startedAt: string; finishedAt: string | null; errorCode: ErrorCode | null }
export type RecoveryAction = "rescan" | "review_conflict" | "restore" | "fix_permissions"
export type RegisterProjectInput = { displayName: string; rootPath: string }
export type RemoveProjectResultDto = { id: string; removed: boolean; nativeConfigurationLeftUnmanaged: boolean }
export type RestorePreview = { previewId: string; snapshotId: string; targetPath: string; currentType: TargetType; snapshotType: TargetType; storageKind: SnapshotStorageKind }
/**
 * 资源应用范围。
 */
export type Scope = "global" | "project"
export type SecretUpdate = { action: "keep" } | { action: "clear" } | { action: "replace"; value: string }
export type SensitiveJsonUpdate = { action: "keep" } | { action: "clear" } | { action: "replace"; value: JsonValue }
export type SensitiveMapUpdate = { action: "keep" } | { action: "clear" } | { action: "replace"; value: Partial<{ [key in string]: string }> }
export type SetGlobalMcpAssignmentInput = { tool: Tool; mcpId: string; assigned: boolean; rowVersion: number }
/**
 * 全局启用/停用一份提示词档案到指定工具；每工具至多一份生效，
 * 启用新档案会自动替换该工具的原生效档案。
 */
export type SetGlobalPromptAssignmentInput = { tool: Tool; promptProfileId: string; assigned: boolean; rowVersion: number }
export type SetGlobalSkillAssignmentInput = { tool: Tool; skillId: string; assigned: boolean; rowVersion: number }
export type SetProjectMcpAssignmentInput = { projectId: string; tool: Tool; mcpId: string; assigned: boolean; mcpRowVersion: number; projectRowVersion: number }
export type SetProjectSkillAssignmentInput = { projectId: string; tool: Tool; skillId: string; assigned: boolean; skillRowVersion: number; projectRowVersion: number }
export type SetPromptProjectAssignmentInput = { projectId: string; tool: Tool; 
/**
 * `None` 表示解除分配：项目文件保留，应用停止纳管。
 */
promptProfileId: string | null; projectRowVersion: number }
export type SkillContentPreviewDto = { id: string; name: string; skillMd: string; files: string[]; contentHash: string; rowVersion: number }
export type SkillDto = { id: string; name: string; sourcePath: string; centralPath: string; contentHash: string; description: string; status: SkillStatus; diagnosticCode: string | null; globalTools: Tool[]; rowVersion: number }
export type SkillImportCandidateDto = { candidateId: string; name: string; description: string; sourcePaths: string[]; status: SkillImportCandidateStatus; reason: string | null; existingSkillId: string | null; takeoverEligible: boolean; takeoverEntryType: SkillTakeoverEntryType | null }
export type SkillImportCandidateStatus = "importable" | "already_imported" | "name_conflict" | "invalid"
export type SkillImportPreviewDto = { previewId: string | null; tool: Tool; sources: SkillImportSourceDto[]; candidates: SkillImportCandidateDto[]; message: string | null }
export type SkillImportResultDto = { tool: Tool; createdCount: number }
export type SkillImportSourceDto = { kind: SkillImportSourceKind; path: string; status: SkillImportSourceStatus; diagnosticCode: string | null; message: string | null }
export type SkillImportSourceKind = "claude_global" | "codex_home" | "codex_agents" | "cursor_home" | "cursor_agents"
export type SkillImportSourceStatus = "ready" | "missing" | "empty" | "unavailable"
export type SkillProjectDto = { id: string; displayName: string; rootPath: string; codexTrustStatus: TrustStatus; rowVersion: number }
export type SkillProjectOptionDto = { skillId: string; name: string; status: SkillStatus; state: SkillProjectSelectionState; selectable: boolean; rowVersion: number }
export type SkillProjectOptionsInput = { projectId: string; tool: Tool }
export type SkillProjectSelectionState = "inherited" | "selected" | "available"
export type SkillStatus = "ready" | "invalid" | "missing"
export type SkillTakeoverEntryType = "external_symlink" | "directory"
export type SkillTakeoverPreviewResultDto = { tool: Tool; assignedCount: number; reusedCount: number; plan: PreviewPlan }
export type SkillTargetStatusDto = { tool: Tool; projectId: string | null; targetPath: string | null; status: SyncStatus; diagnosticCode: string | null }
export type SnapshotDeleteFailureDto = { snapshotId: string; code: string; message: string }
export type SnapshotRestoreInput = { snapshotId: string }
export type SnapshotStorageKind = "payload_file" | "metadata_only" | "directory_tree"
export type SnapshotSummary = { snapshotId: string; runId: string; targetId: string | null; targetPath: string; targetType: TargetType; storageKind: SnapshotStorageKind; restorable: boolean; createdAt: string }
export type SymlinkPolicy = "reject" | "managed_children_only"
export type SyncRunKind = "preview" | "apply" | "restore"
export type SyncRunStatus = "previewed" | "applying" | "restoring" | "succeeded" | "failed" | "stale" | "rolled_back" | "rollback_failed"
/**
 * 原生目标相对最近一次受管基线的状态。
 */
export type SyncStatus = "in_sync" | "external_non_owned_change" | "external_owned_change" | "missing" | "parse_error" | "permission_denied" | "policy_blocked" | "untrusted" | "target_type_changed" | "failed"
export type TargetCapability = { state: CapabilityState; diagnosticCode: string | null }
/**
 * Adapter 对一个原生目标的完整只读合同。
 */
export type TargetDescriptor = { tool: Tool; artifactKind: ArtifactKind; scope: Scope; projectRoot: string | null; path: string | null; format: TargetFormat; managedSelectorRoots: string[]; sensitiveSelectors: string[]; capability: TargetCapability; policy: PolicyState; trust: TargetTrustState; promptOverride: PromptOverrideState; symlinkPolicy: SymlinkPolicy }
export type TargetFormat = "json" | "toml" | "markdown" | "symlink_directory"
export type TargetTrustState = "not_required" | "trusted" | "untrusted" | "unknown"
export type TargetType = "file" | "directory" | "symlink" | "missing"
/**
 * 正式支持的原生工具。
 */
export type Tool = "claude" | "codex" | "cursor"
export type ToolAvailabilityState = "installed" | "unavailable" | "unsupported"
export type ToolProfileStatusDto = { tool: Tool; availability: ToolAvailabilityState; installationVersion: string | null; providerTargetPath: string | null; promptTargetPath: string | null; providerCapability: TargetCapability; promptCapability: TargetCapability; promptOverride: PromptOverrideState; providerPolicy: PolicyState; newSessionNotice: string; bearerTokenWarning: string | null }
export type TrustStatus = "unknown" | "trusted" | "untrusted"
export type UpdateAppSettingsInput = { applyMode: ApplyMode }
export type UpdateMcpServerInput = { id: string; name: string; transport: McpTransport; command: string | null; args: string[]; url: string | null; headers: SensitiveMapUpdate; env: SensitiveMapUpdate; extra: SensitiveJsonUpdate; enabled: boolean; rowVersion: number }
export type UpdatePromptProfileInput = { id: string; name: string; body: string; rowVersion: number }
export type UpdateProviderProfileInput = { id: string; name: string; apiBaseUrl: string; apiKey: SecretUpdate; defaultModel: string; options: ProviderOptionsInput; rowVersion: number }
export type VersionedMcpInput = { id: string; rowVersion: number }
export type VersionedProfileInput = { id: string; rowVersion: number }
export type VersionedProjectInput = { id: string; rowVersion: number }
export type VersionedSkillInput = { id: string; rowVersion: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
